/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistentRouteImport } from './routes/assistent'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DokumenteRouteImport } from './routes/dokumente'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as KiHinweiseRouteImport } from './routes/ki-hinweise'
import { Route as StatistikRouteImport } from './routes/statistik'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistentRoute = AssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenteRoute = DokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const KiHinweiseRoute = KiHinweiseRouteImport.update({
  id: '/ki-hinweise',
  path: '/ki-hinweise',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/datenschutz': typeof DatenschutzRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/jobs': typeof JobsRoute
  '/ki-hinweise': typeof KiHinweiseRoute
  '/statistik': typeof StatistikRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/datenschutz': typeof DatenschutzRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/jobs': typeof JobsRoute
  '/ki-hinweise': typeof KiHinweiseRoute
  '/statistik': typeof StatistikRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/datenschutz': typeof DatenschutzRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/jobs': typeof JobsRoute
  '/ki-hinweise': typeof KiHinweiseRoute
  '/statistik': typeof StatistikRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistent'
    | '/datenschutz'
    | '/dokumente'
    | '/einstellungen'
    | '/impressum'
    | '/jobs'
    | '/ki-hinweise'
    | '/statistik'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistent'
    | '/datenschutz'
    | '/dokumente'
    | '/einstellungen'
    | '/impressum'
    | '/jobs'
    | '/ki-hinweise'
    | '/statistik'
  id:
    | '__root__'
    | '/'
    | '/assistent'
    | '/datenschutz'
    | '/dokumente'
    | '/einstellungen'
    | '/impressum'
    | '/jobs'
    | '/ki-hinweise'
    | '/statistik'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistentRoute: typeof AssistentRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DokumenteRoute: typeof DokumenteRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ImpressumRoute: typeof ImpressumRoute
  JobsRoute: typeof JobsRoute
  KiHinweiseRoute: typeof KiHinweiseRoute
  StatistikRoute: typeof StatistikRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistent': {
      id: '/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumente': {
      id: '/dokumente'
      path: '/dokumente'
      fullPath: '/dokumente'
      preLoaderRoute: typeof DokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ki-hinweise': {
      id: '/ki-hinweise'
      path: '/ki-hinweise'
      fullPath: '/ki-hinweise'
      preLoaderRoute: typeof KiHinweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistentRoute: AssistentRoute,
  DatenschutzRoute: DatenschutzRoute,
  DokumenteRoute: DokumenteRoute,
  EinstellungenRoute: EinstellungenRoute,
  ImpressumRoute: ImpressumRoute,
  JobsRoute: JobsRoute,
  KiHinweiseRoute: KiHinweiseRoute,
  StatistikRoute: StatistikRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
